W6D4/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W6D4/ninety_nine_cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  Cat_colors = [
    'orange', 'white', 'grey', 'black', 
    'mixed-color', 'light-brown', 'brown'
  ]

  Sex = ["M", "F"]

  validates :color, inclusion: Cat_colors
  validates :sex, inclusion: Sex
  validates :birth_date, :color, :name, :sex, presence: true
  
  def age
    birthday = self.birth_date
    return ((Time.zone.now - birthday.to_time) / 1.year.seconds).floor
  end
end

W6D4/ninety_nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUS_STATES = %w(APPROVED DENIED PENDING).freeze

  validates :cat_id, :end_date, :start_date, :status, presence: true
  validates :status, inclusion: STATUS_STATES
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  belongs_to :cat

  after_initialize :assign_pending_status

  def approve!
    raise 'not pending' unless self.status == 'PENDING'
    transaction do
      self.status = 'APPROVED'
      self.save!

      overlapping_pending_requests.each do |req|
        req.update!(status: 'DENIED')
      end
    end
  end

  def approved?
    self.status == 'APPROVED'
  end

  def denied?
    self.status == 'DENIED'
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end

  private

  def assign_pending_status
    self.status ||= 'PENDING'
  end

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date',
                 start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where('status = \'APPROVED\'')
  end

  def overlapping_pending_requests
    overlapping_requests.where('status = \'PENDING\'')
  end

  def does_not_overlap_approved_request
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        'Request conflicts with existing approved request'
    end
  end

  def start_must_come_before_end
    return if start_date < end_date
    errors[:start_date] << 'must come before end date'
    errors[:end_date] << 'must come after start date'
  end
end

W6D4/ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new
  end

  private

  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

W6D4/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private
  
  def cat_params
    params.require(:cat).permit(
      :birth_date, 
      :color, 
      :name, 
      :sex, 
      :description
      )
  end
end

W6D4/ninety_nine_cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

W6D4/ninety_nine_cats/app/views/cats/_cat.html.erb
<li><a href=<%="/cats/#{cat.id}"%>><%= cat.name %></a></li>
<li><%= cat.birth_date %></li>
<li><%= cat.color %></li>
<li><%= cat.sex %></li>
<li><%= cat.description %></li>

W6D4/ninety_nine_cats/app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
  <% button_text = "Create cat" %>
<% elsif type == :edit %>
  <% action_url = cat_url(cat.id) %>
  <% button_text = "Update cat" %>
<% end %>


<form action="<%= action_url %>" method="POST">

  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="cat_name">Name</label>
  <input 
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>"
  >

  <br>

  <label for="cat_birth_date">Birth date</label>
  <input 
  type="date"
  name="cat[birth_date]"
  id="cat_birth_date"
  value="<%= cat.birth_date %>">
  
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
  <option disabled selected>--select a color--</option>
    <% Cat::Cat_colors.each do|color| %>
      <option 
        <%= cat.color == color ? "selected" : "" %>
        value="<% color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>
  
  <label for="cat_sex">Sex</label>
  <input 
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">M</label>
  <input 
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">F</label>
  <br>
  
  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>
  <br>

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
  
</form>

W6D4/ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Form to update a cat</h1>

<%= render "form", {cat: @cat, type: :edit} %>

W6D4/ninety_nine_cats/app/views/cats/index.html.erb
<h1>All of the cats!</h1>

<% @cats.each do |cat| %>
<ul>
  <%= render "cat", {cat: cat} %>
</ul>

<% end %>

W6D4/ninety_nine_cats/app/views/cats/new.html.erb
<h1>Form to register a new cat :)</h1>

<%= render "form", {cat: @cat, type: :new} %>

W6D4/ninety_nine_cats/app/views/cats/show.html.erb
<!---
<%#= render "cat", {cat: @cat} %>
<li><a href="<%#= cats_url %>">Return to all cats</a></li>
--->


<table>
  <thead>
    <tr>
      <th colspan = "2"><%= @cat.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cat.name %>'s birthday: <%= @cat.birth_date %></td>
      <td>fur color: <%= @cat.color %></td>
      <td>sex: <%= @cat.sex %></td>
    </tr>
  </tbody>
  <tfoot>
    <th>About <%= @cat.name %>:</th>
    <td><%= @cat.description %></td>
  </tfoot>
</table> 
<li><a href="<%= cats_url %>">Return to all cats</a></li>

W6D4/ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>